import type { ImgMeta } from '^types';

import image_1 from '^^assets/images/paintings/1.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_2 from '^^assets/images/paintings/2.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_3 from '^^assets/images/paintings/3.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_4 from '^^assets/images/paintings/4.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_5 from '^^assets/images/paintings/5.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_6 from '^^assets/images/paintings/6.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_8 from '^^assets/images/paintings/8.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_9 from '^^assets/images/paintings/9.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_10 from '^^assets/images/paintings/10.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_11 from '^^assets/images/paintings/11.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_13 from '^^assets/images/paintings/13.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_14 from '^^assets/images/paintings/14.jpg?w=1100&format=avif;webp;jpg&as=picture&imagetools';
import image_15 from '^^assets/images/paintings/15.jpg?w=641&format=avif;webp;jpg&as=picture&imagetools';
import image_16 from '^^assets/images/paintings/16.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_18 from '^^assets/images/paintings/18.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_20 from '^^assets/images/paintings/20.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_21 from '^^assets/images/paintings/21.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_22 from '^^assets/images/paintings/22.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_23 from '^^assets/images/paintings/23.jpg?w=640&format=avif;webp;jpg&as=picture&imagetools';
import image_24 from '^^assets/images/paintings/24.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_27 from '^^assets/images/paintings/27.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_28 from '^^assets/images/paintings/28.jpg?w=740&format=avif;webp;jpg&as=picture&imagetools';
import image_29 from '^^assets/images/paintings/29.jpg?w=1500&format=avif;webp;jpg&as=picture&imagetools';
import image_30 from '^^assets/images/paintings/30.jpg?w=1100&format=avif;webp;jpg&as=picture&imagetools';
import image_32 from '^^assets/images/paintings/32.jpg?w=940&format=avif;webp;jpg&as=picture&imagetools';
import image_33 from '^^assets/images/paintings/33.jpg?w=844&format=avif;webp;jpg&as=picture&imagetools';
import image_34 from '^^assets/images/paintings/34.jpg?w=844&format=avif;webp;jpg&as=picture&imagetools';
import image_35 from '^^assets/images/paintings/35.jpg?w=2841&format=avif;webp;jpg&as=picture&imagetools';

export const paintings = {
	1: image_1 as ImgMeta,
	2: image_2 as ImgMeta,
	3: image_3 as ImgMeta,
	4: image_4 as ImgMeta,
	5: image_5 as ImgMeta,
	6: image_6 as ImgMeta,
	8: image_8 as ImgMeta,
	9: image_9 as ImgMeta,
	10: image_10 as ImgMeta,
	11: image_11 as ImgMeta,
	13: image_13 as ImgMeta,
	14: image_14 as ImgMeta,
	15: image_15 as ImgMeta,
	16: image_16 as ImgMeta,
	18: image_18 as ImgMeta,
	20: image_20 as ImgMeta,
	21: image_21 as ImgMeta,
	22: image_22 as ImgMeta,
	23: image_23 as ImgMeta,
	24: image_24 as ImgMeta,
	27: image_27 as ImgMeta,
	28: image_28 as ImgMeta,
	29: image_29 as ImgMeta,
	30: image_30 as ImgMeta,
	32: image_32 as ImgMeta,
	33: image_33 as ImgMeta,
	34: image_34 as ImgMeta,
	35: image_35 as ImgMeta
};
